# .github/workflows/python_cron_job.yml

name: GET IP ADDRESS

# This workflow will run every 30 minutes
on:
  push:

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      # Step 1: Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you want

      # Step 3: Run the Python script
      - name: Run Python script
        run: python getip.py